# Set universal environment variables needed on all workstations

# Ansible, Python, and git project paths
ANSIBLE_VAULTS=$HOME/.ansible/vaults
PROJECTSDIR=$HOME/Projects
PYENV_PATH=$HOME/.local/lib/python

# System CA Trust paths for Python to accept
SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
